#!/bin/bash
#gunzip var/log/*.gz

echo "sosreport contains data related the following KBs"

for i in ~/scripts/myscripts/csr2/plugins/*
    do
        if $i > /dev/null; then
	    echo " -> https://access.redhat.com/solutions/${i#/home/gfigueir/scripts/myscripts/csr2/plugins/KB}"
	fi
done
