#!/bin/bash

echo "sosreport contains data related the following KBs"

cd $1

for i in ~/myscripts/csr2/plugins/*
    do
        if $i > /dev/null; then
            j=${i#/root/myscripts/csr2/plugins/}
	    DESC=$(grep $j ~/myscripts/csr2/kb.db)
	    echo -n " -> https://access.redhat.com/solutions/${i#/root/myscripts/csr2/plugins/KB} - "
	    echo ${DESC:12}
	fi
done
